### ISSUE TITLE
clean install and run

### ISSUE THREAD

**Issue by JasonGellis** [alan-turing-institute/Palaeoanalytics#114]
# python native virtual environment install and run
1st install from a computer with only python 3.8.2 installed.

- [x] `python3 -m venv paleo`  
- [x] `source paleo/bin/activate`   
- [x] `git clone https://github.com/alan-turing-institute/Palaeoanalytics.git`
- [x] `cd Palaeoanalytics`
- [x] `git checkout develop`  **<- not needed in python virtual environment as git clone puts you into develop**
- [x] `pip install opencv-python` **<- README.md only says opencv, which throws an error**    
- [x] `pip install .` **<- Using legacy 'setup.py install' for pylithics, since package 'wheel' is not installed.**
- [x] `pylithics_run --help` **<- throws error:**
Traceback (most recent call last):
  File "/Users/palaeoanalytics/paleo/bin/pylithics_run", line 11, in <module>
    load_entry_point('pylithics==1.0', 'console_scripts', 'pylithics_run')()
  File "/Users/palaeoanalytics/paleo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/palaeoanalytics/paleo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/Users/palaeoanalytics/paleo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/palaeoanalytics/paleo/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/palaeoanalytics/paleo/lib/python3.8/site-packages/pylithics/scripts/run.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

# python Conda virtual environment install and run following instructions from README.md
1st install from a computer with python 3.8.2 and miniconda installed

- [x] `conda create -n paleo python=3.7`  
- [x] `conda activate paleo`   
- [x] `git clone https://github.com/alan-turing-institute/Palaeoanalytics.git`
- [x] `cd Palaeoanalytics`
- [x] `git checkout develop`  **<- not needed in Conda virtual environment as git clone puts you into develop**
- [x] `conda install -c conda-forge opencv` **<- miniconda installs py-opencv-3.4.2**    
- [x] `pip install .`
- [x] `pylithics_run --help` **<- throws error:**
Traceback (most recent call last):
  File "/Users/palaeoanalytics/opt/miniconda3/envs/paleo/bin/pylithics_run", line 5, in <module>
    from pylithics.scripts.run import main
  File "/Users/palaeoanalytics/opt/miniconda3/envs/paleo/lib/python3.7/site-packages/pylithics/scripts/run.py", line 4, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by crangelsmith** [comment]
I think we are missing a library, what happens if you add pyyaml to the requirement.txt file and run it again?

**Comment by JasonGellis** [comment]
requirement.txt was updated and solved this issue

**Comment by crangelsmith** [comment]
Hi @crangelsmith, could you try to run the steps in the first comment in the version from `main`, I'm trying to address the comments from #130 but my the `pip install .` gets stuck installing `opencv-python` with the message:

 > Building wheel for opencv-python (PEP 517) ... /

**Comment by JasonGellis** [comment]
This issue has now beed addressed in the README.md
